INFO:app:Database configuration set with URL from environment
[2025-04-03 18:56:45 +0200] [4633] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2: CREATE TABLE playlist (
                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jakob/git/KidsAudioPlayer/main.py", line 1, in <module>
    from app import app
  File "/home/jakob/git/KidsAudioPlayer/app.py", line 37, in <module>
    db.create_all()
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 900, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", line 881, in _call_for_binds
    getattr(metadata, op_name)(bind=engine)
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 5925, in create_all
    bind._run_ddl_visitor(
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3249, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2456, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 981, in visit_metadata
    self.traverse_single(
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 664, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 1019, in visit_table
    )._invoke_with(self.connection)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 321, in _invoke_with
    return bind.execute(self)
           ^^^^^^^^^^^^^^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 187, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1527, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/jakob/git/KidsAudioPlayer/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for schema public
LINE 2: CREATE TABLE playlist (
                     ^

[SQL: 
CREATE TABLE playlist (
	id SERIAL NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2025-04-03 18:56:45 +0200] [4633] [INFO] Worker exiting (pid: 4633)
[2025-04-03 18:56:46 +0200] [4632] [ERROR] Worker (pid:4633) exited with code 3
[2025-04-03 18:56:46 +0200] [4632] [ERROR] Shutting down: Master
[2025-04-03 18:56:46 +0200] [4632] [ERROR] Reason: Worker failed to boot.